title: "VDTC"
theme: minima
markdown: kramdown
plugins:
  - jekyll-feed
description: "Justice for Tigray"
baseurl: ""
url: "https://vdtctigray.github.io"
theme: minima

navbar:
  - name: "Home"      link: "/"
  - name: "Letters"   link: "/letters"
  - name: "Gallery"   link: "/gallery"
  - name: "Videos"    link: "/videos"
  - name: "About"     link: "/about"
  - name: "Support"   link: "/support"
